name: Publish Docker Images

on:
  workflow_call:

jobs:
  docker-compose-push:
    name: Docker Compose Push
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login --username="$USERNAME" --password="$PASSWORD"

      - name: Build Docker images
        run: |
          docker compose --file ./infra/docker/docker-compose.yaml build

      - name: Push Docker images
        run: |
          docker compose --file ./infra/docker/docker-compose.yaml push
